name: push image

on:
  push:
    branches: ["main"]

env:
  AWS_ACCOUNT_ID:	939095374446
  AWS_REGION: us-west-2
  ECR_REPOSITORY: config-manager

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secrets-access-key: ${ secrets.AWS_SECRET_ACCESS_KEY}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
      
      - name: Login ECR
        run: |
          aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 939095374446.dkr.ecr.us-west-2.amazonaws.com
      
      - name: build image
        run: |
          IMAGE_URL="${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY}}:${{ github.sha}}"
          docker build -t $IMAGE_URL .
          echo "IMAGE_URL=$IMAGE_URL" >> $GITHUB_ENV
      
      - name: push ECR
        run: |
          docker push ${{ env.IMAGE_URL}}